version: '3'
services:
    db:
        restart: always
        image: postgres
        container_name: postgres
        volumes:
          - ./pgdata:/var/lib/postgresql/data
        ports:
          - "8001:5432"
        environment:
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_USER=postgres
    auth_service:
        build: ./back_go/auth_service
        restart: always
        environment:
          - DBHOST=db
          - USER=postgres
          - PASSWORD=postgres
          - DBNAME=mrdocker
          - DBPORT=5432
        expose:
            - 23001
        ports:
            - "23001:23001"
        depends_on:
            - db
    nista-front:
        build: ./nistagram-front
        restart: always
        #environment:
        expose:
            - 4200
        ports:
            - "4200:4200"
    bezbednost:
        build: ./bezbednost
        restart: always
        ports:
            - "8443:8443"
        depends_on:
            - db
volumes:
    pgdata:
