INSERT INTO KEY_STORE (KS_ID, KS_FILE_NAME, KS_PASSWORD) VALUES (1, 'root', 'root');
INSERT INTO KEY_STORE (KS_ID, KS_FILE_NAME, KS_PASSWORD) VALUES (2, 'inter', 'inter');
INSERT INTO KEY_STORE (KS_ID, KS_FILE_NAME, KS_PASSWORD) VALUES (3, 'end', 'end');